spring:
  application:
    name: foundation-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hydrogenhr?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: developer
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        generate_statistics: true
        format_sql: true
    database: mysql
    open-in-view: true
  flyway:
    user: developer
    password: password@123
    url: jdbc:mysql://127.0.0.1:3306/hydrogenhr?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    locations: classpath:db/migration
    driver-class-name: com.mysql.cj.jdbc.Driver
    enabled: false
  cloud:
    vault:
      kv:
        enabled: false
        backend: secret
        default-context: ${spring.application.name}
      uri: http://127.0.0.1:8200
      token: ${SPRING_VAULT_TOKEN}
      authentication: token
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 20s
  threads:
    virtual:
      enabled: true
management:
  server:
    port: 8091
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: '*'
server:
  servlet:
    context-path: /api/v1
  port: 8099
  shutdown: graceful
logging:
  level:
    sql: warn
    org.springframework: warn
    org.hibernate: warn
    com.hydrogenhr: info
springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  salt:
    strength: 10
    secret: 729e344a01e52c822bdfdec61e28d6eda02658d2e7d2b80a9b9029f41e212dde
    length: 1024
    iterations: 4
    cpu-cost: 8
    memory-cost: 12
    parallelization: 4
    hash-length: 32
    memory: 4096
  security:
    jwt-endpoint: http://localhost:8099/api/v1
    issuer: http://localhost:8099/api/v1
