CREATE TABLE users (
    is_admin                 BOOLEAN,
    password_reset           BOOLEAN,
    using_2fa                BOOLEAN,
    application_fk           BIGINT,
    country_fk               BIGINT,
    created_at               TIMESTAMP(6),
    id                       BIGINT NOT NULL PRIMARY KEY,
    password_last_reset_date TIMESTAMP(6),
    updated_at               TIMESTAMP(6),
    account_type             VARCHAR(15) CHECK (account_type IN ('SERVICE_ACCOUNT', 'NORMAL_ACCOUNT')),
    telephone                VARCHAR(16),
    first_name               VARCHAR(50),
    last_name                VARCHAR(50),
    middle_name              VARCHAR(50),
    username                 VARCHAR(100) UNIQUE,
    email                    VARCHAR(120) UNIQUE,
    secret                   VARCHAR(150),
    created_by               VARCHAR(255),
    password                 BLOB,
    status                   VARCHAR(255) CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELED', 'LOCKED')),
    updated_by               VARCHAR(255),
    CONSTRAINT FK_tbl_applications_tbl_users_col_organization_id FOREIGN KEY (application_fk) REFERENCES organizations(id),
    CONSTRAINT FK_tbl_countries_tbl_users_col_country_id FOREIGN KEY (country_fk) REFERENCES countries(id)
);
